### PR TITLE
Allow luminance map to be reused

### PR DESCRIPTION
**Pull request by Iwasawafag**
What's changed:

- Code was refactored. Types moved into separate CommonJS Modules, main algorithm now converted into OOP class as well. Public API is backwards compatible
- `loadImage` method does not perform comparison of pixel's liminance to a treshold anymore. 
Instead luminance values are recorded to `Bitmap` as is (which `data` property type was changed from `Int8Array` to `Uint8Array`). 

  Comparison to treshold (`blacklevel` setting) now performed later in `process` method, which allows us to re-process image with different parameters, without having to reload the raster image
- In case if `loadImage` method (on a single Potrace instance) was called before previous image was loaded - all previous calls will receive an error.

More changes is on the way

### CODE REVIEW

**Comment by Iwasawafag** [comment]
Also improved how transparent regions are handled. 

Before:


After 5891471:

**Comment by tooolbox** [comment]
Excellent!  I'm adding you as a collaborator in case you have anything further you want to add.

**Comment by Iwasawafag** [comment]
I do have few more changes in plans indeed. Not sure if you're gonna like them or not, though. Currently it's WIP, can be found in [api_changes](https://github.com/Iwasawafag/node-potrace/tree/api_changes) branch: 

#### Already in that branch:

- Having public `process` method seemed unnecessary, so has been removed removed. Since it's synchonous as well as `getSVG` it's automatically performed when needed (always on first call and later when parameters changes) 
- Dropped backward compatibility code
- Added Posterizer class that uses Potrace to create images with two or more layers of different transparency. Can create something like this http://i.imgur.com/pi8Of0E.png
- Added an option allowing to switch what tones Potrace will look for on the image from darkest to brightest ones (assuming it will be displayed over dark background) ([example](http://i.imgur.com/ifqjZWO.png))

#### In plans

- Add `getSymbol` method to both, Potrace and Posterizer classes, providing a more convinient way of exporting vector to a `<symbol>`, that could be easily used later on a web pages with help of `<use>` tag
- Maybe rename some parameters and/or classes. `samples` to something like `steps` and `whiteOnBlack` to `invert`
- Implement another option to Posterizer, controlling how colors will be distributed across steps. I would like it to be able automatically find the best way to place color stops, rather than evenly splitting given range
- Bump version and file a merge request

**Comment by tooolbox** [comment]
That's some great work.  I definitely have no problem with you adding more functionality, and as you say we can bump the major version with these API changes.

I don't have time to dev on this thing right now, and you're bringing a lot to the table, so the collaborator invitation stands.  If you prefer to stick with the merge request workflow that's also fine.  Either way, bring it to my attention if you bump the version, and I'll publish to NPM.

**Pull request merged**
