### PR TITLE
fix: trim "path"

### PR DESCRIPTION
**Pull request by privatenumber**
The calculated path always had a trailing space behind it.

### CODE REVIEW

**Comment by pklauzinski** [comment]
Ran into this issue as well. Any chance this PR can be merged?

**Comment by tooolbox** [comment]
Looks good to me.

**Comment by tooolbox** [comment]
@Iwasawafag you'll need to pull this in & publish I suppose.

**Comment by privatenumber** [comment]
Hard to tell which repo is the source of truth, @tooolbox  or @Iwasawafag s.

For what it's worth, I made the PR against @tooolbox 's because the npm package [`potrace`](https://www.npmjs.com/package/potrace) is by [mattmc](https://www.npmjs.com/package/potrace) (@tooolbox), which is what my packages depend on.

**Comment by pklauzinski** [comment]
Yep, this is the repo for the registered NPM package, and it gets a lot of downloads too.

@tooolbox I see you bumped the version.. if you publish it to NPM that should update the package.

Or does @Iwasawafag own the NPM account? This is confusing.

**Comment by tooolbox** [comment]
I added him as an owner on NPM a while ago, as I didn't want to maintain it.  But it doesn't seem that he's been amazing about accepting PRs, or answering pings on GitHub.

It has been a long time since I've published anything on NPM, but I figured it out and published `v2.1.4`.

**Comment by pklauzinski** [comment]
Thank you, sir!

**Pull request merged**
